[mgr]
ratio = [3, 5, 10]

[opener]
play = [ { run = '/home/daroch/.config/yazi/play.sh "$@"', orphan = true } ]
open = [ { run = '/home/daroch/.config/yazi/image.sh "$@"', orphan = true } ]

[manager]
sort_by      = "mtime"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
