# Normal
color0       #0b1016   
color1       #bc4a64   
color2       #50C878   
color3       #bdcda5
color4       #73C2FB
color5       #AFDBF5
color6       #00cdcd   
color7       #e5e5e5   

# Bright
color8       #2c3b47   
color9       #ec3f54   
color10      #7fd1c6   
color11      #c3cf8c   
color12      #1093C3
color13      #b29bff   
color14      #00ffff   
color15      #ffffff   
