# Normal
color0       #0b1016   
color1       #b14a64   
color2       #50C878   
color3       #6695AB
color4       #1093C3
color5       #2C97C2
color6       #3f70a0   
color7       #b9c7d4   

# Bright
color8       #2c3b47   
color9       #d16c86   
color10      #6fd1d0   
color11      #c3cf8c   
color12      #1093C3
color13      #b29bff   
color14      #8deaff   
color15      #adf6ff   
