# Normal colors
color0  #000000   # black
color1  #cd0000   # red
color2  #00cd00   # green
color3  #cdcd00   # yellow
color4  #0000ee   # blue
color5  #cd00cd   # magenta
color6  #00cdcd   # cyan
color7  #e5e5e5   # white (light gray)

# Bright colors
color8  #7f7f7f   # bright black (dark gray)
color9  #ff0000   # bright red
color10 #00ff00   # bright green
color11 #ffff00   # bright yellow
color12 #5c5cff   # bright blue
color13 #ff00ff   # bright magenta
color14 #00ffff   # bright cyan
color15 #ffffff   # bright white
