# Shell variables
# Generated by 'wal'
wallpaper='/home/daroch/Pictures/wallpaper/Taj-Mahal.jpg'

# Special
background='#11130f'
foreground='#c0d2e2'
cursor='#c0d2e2'

# Colors
color0='#11130f'
color1='#0974B2'
color2='#528BA3'
color3='#168FCF'
color4='#61A6D8'
color5='#D1B099'
color6='#CCC2B8'
color7='#c0d2e2'
color8='#86939e'
color9='#0974B2'
color10='#528BA3'
color11='#168FCF'
color12='#61A6D8'
color13='#D1B099'
color14='#CCC2B8'
color15='#c0d2e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
