foreground   #c0d2e2
background   #11130f
cursor       #c0d2e2

color0       #11130f
color8       #86939e
color1       #0974B2
color9       #0974B2
color2       #528BA3
color10      #528BA3
color3       #168FCF
color11      #168FCF
color4       #61A6D8
color12      #61A6D8
color5       #D1B099
color13      #D1B099
color6       #CCC2B8
color14      #CCC2B8
color7       #c0d2e2
color15      #c0d2e2
