--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/daroch/Pictures/wallpaper/Taj-Mahal.jpg"

-- Special
background="#11130f"
foreground="#c0d2e2"
cursor="#c0d2e2"

-- Colors
color0="#11130f"
color1="#0974B2"
color2="#528BA3"
color3="#168FCF"
color4="#61A6D8"
color5="#D1B099"
color6="#CCC2B8"
color7="#c0d2e2"
color8="#86939e"
color9="#0974B2"
color10="#528BA3"
color11="#168FCF"
color12="#61A6D8"
color13="#D1B099"
color14="#CCC2B8"
color15="#c0d2e2"
