$background = rgb(11130f)
$foreground = rgb(c0d2e2)
$color0 = rgb(11130f)
$color1 = rgb(0974B2)
$color2 = rgb(528BA3)
$color3 = rgb(168FCF)
$color4 = rgb(61A6D8)
$color5 = rgb(D1B099)
$color6 = rgb(CCC2B8)
$color7 = rgb(c0d2e2)
$color8 = rgb(86939e)
$color9 = rgb(0974B2)
$color10 = rgb(528BA3)
$color11 = rgb(168FCF)
$color12 = rgb(61A6D8)
$color13 = rgb(D1B099)
$color14 = rgb(CCC2B8)
$color15 = rgb(c0d2e2)
