# exec-once = hyprctl setcursor Adwaita 24

cursor {
    inactive_timeout = 3.0 # Hides the cursor after 3 seconds of inactivity
}

exec-once = hyprctl setcursor Adwaita 24
env = HYPRCURSOR_THEME,...
env = XCURSOR_THEME,...
